<?php

function groceries_menu()
{
  $items = array();
  $items['groceries'] = array(
    'title' => "Welcome to the Grocery List!",
    'page callback' => 'grocery_list',
    'access callback' => TRUE,
    'type' => MENU_NORMAL_ITEM,
  );
  return $items;
}

function make_grocery_list()
{
  $grocery_list['eggs'] = array(
    'price' => 1.99,
    'quantity' => 2,
  );

  $grocery_list['milk'] = array(
    'price' => 2.99,
    'quantity' => 1,
  );

  return $grocery_list;
}

function grocery_list()
{
  $groceries = make_grocery_list();
  $list = '';
  $price = 1;

  foreach($groceries as $grocery_to_buy_key => $grocery_descriptive_componants){
    $list .= '<p>' . $grocery_to_buy_key .'</p>';
    foreach($grocery_descriptive_componants as $description_key => $specific){
      $price *= $specific;
      $list .= '
          <ul>
            <li>' . $description_key . ': ' . $specific . '</li>
          </ul>
      ';
    }
    //Set list price outside of the description key loop:
    $list .= ' <p> Total for item: ' . $price . '</p> ';
    //Then the $price beloe this resets the value to one before looping through again for the next field.
    $price = 1;

  }
  return $list;
}
