<?php

function groceries_menu()
{
  $items = array();
  $items['groceries'] = array(
    'title' => "Welcome to the Grocery List!",
    'page callback' => 'grocery_list',
    'access callback' => TRUE,
    'type' => MENU_NORMAL_ITEM,
  );
  return $items;
}

function make_grocery_list()
{
  $grocery_list['eggs'] = array(
    'price' => 1.99,
    'quantity' => 2,
  );

  $grocery_list['milk'] = array(
    'price' => 2.99,
    'quanitity' => 1,
  );

  return $grocery_list;
}

function grocery_list()
{
  $groceries = make_grocery_list();
  $list = '';

  foreach($groceries as $grocery_to_buy_key => $grocery_descriptive_componant){
    $list .= '<p>' . $grocery_to_buy_key .'</p>';
    foreach($grocery_descriptive_componant as $description_key => $specific){
      $list .= '
          <ul>
            <li>' . $description_key . ': ' . $specific . '</li>
          </ul>
      ';
    }
  }
  return $list;
}

// function grocery_list()
// {
//   $groceries = make_grocery_list();
//   $list = '';
//
//   foreach($groceries as $grocery_item_key => $grocery_item_value){
//     $list .= '<p>' . $grocery_item_key .'</p>';
//     foreach($grocery_item_value as $key => $value){
//       $list .= '
//           <ul>
//             <li>' . $key . ': ' . $value . '</li>
//           </ul>
//       ';
//     }
//   }
//   return $list;
// }
