<?php

function comment_buddy() {
  $items = array();
  $items ['comment'] = array(
    'title' => 'Comment Buddy',
    'access callback' => TRUE,
    'type' => MENU_NORMAL_ITEM,
    'page callback' =>  'comment_submit',
  );

  return $items;
}


function comment_buddy_comment_insert() {
  drupal_set_message('Thank you, your comment submitted!');
}

function comment_buddy_comment_update() {
  drupal_set_message('Thank you, your comment has been updated!');
}


function comment_buddy_comment_delete() {
  drupal_set_message("Your comment has been deleted!");
}
