<?php

function hello_user_menu() {
  $items = array();
  $items['hello_human'] = array(
    'title' => "Hello Human!",
    'page callback' => 'hello_new_user',
    'access callback' => TRUE,
    'type' => MENU_NORMAL_ITEM,
  );
  return $items;
}

function hello_new_user() {
  return '<p> welcome new user qwfq2dq3edq3df3q4f4  </p>';
}

function hello_user_user_insert() {
  $_GET['destination'] = "hello_human";
}
